//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvernessPark.Utilities.NMEA {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InvernessPark.Utilities.NMEA.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to °.
        /// </summary>
        internal static string degrees {
            get {
                return ResourceManager.GetString("degrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Positioning System Fix Data.
        /// </summary>
        internal static string gga {
            get {
                return ResourceManager.GetString("gga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satellite status.
        /// </summary>
        internal static string gsa {
            get {
                return ResourceManager.GetString("gsa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS Pseudorange Noise Statistics.
        /// </summary>
        internal static string gst {
            get {
                return ResourceManager.GetString("gst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satellites in view.
        /// </summary>
        internal static string gsv {
            get {
                return ResourceManager.GetString("gsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NMEA heading log.
        /// </summary>
        internal static string hdt {
            get {
                return ResourceManager.GetString("hdt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended Minimum data for gps.
        /// </summary>
        internal static string rmc {
            get {
                return ResourceManager.GetString("rmc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track made good and ground speed.
        /// </summary>
        internal static string vtg {
            get {
                return ResourceManager.GetString("vtg", resourceCulture);
            }
        }
    }
}
